## IMPORTING LIBRARIES

In [1]:
import pandas as pd
import numpy as np

# Display settings
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)

## LOAD THE DATASET

In [9]:
sales2020 = pd.read_csv("C:/Users/DELL/OneDrive/Desktop/apexplanet2/dataset/raw/AdventureWorks Sales Data 2020.csv")
sales2021 = pd.read_csv("C:/Users/DELL/OneDrive/Desktop/apexplanet2/dataset/raw/AdventureWorks Sales Data 2021.csv")
sales2022 = pd.read_csv("C:/Users/DELL/OneDrive/Desktop/apexplanet2/dataset/raw/AdventureWorks Sales Data 2022.csv")

In [10]:
print("Sales 2020 Shape:", sales2020.shape)
print("Sales 2021 Shape:", sales2021.shape)
print("Sales 2022 Shape:", sales2022.shape)

Sales 2020 Shape: (2630, 8)
Sales 2021 Shape: (23935, 8)
Sales 2022 Shape: (29481, 8)

## PREVIEW THE DATA

In [11]:
sales2020.head()
sales2021.head()
sales2022.head()

,OrderDate,StockDate,OrderNumber,ProductKey,CustomerKey,TerritoryKey,OrderLineItem,OrderQuantity
0,2022-01-01,2021-12-13,SO61285,529,23791,1,2,2
1,2022-01-01,2021-09-24,SO61285,214,23791,1,3,1
2,2022-01-01,2021-09-04,SO61285,540,23791,1,1,1
3,2022-01-01,2021-09-28,SO61301,529,16747,1,2,2
4,2022-01-01,2021-10-21,SO61301,377,16747,1,1,1

##  CHECKING COLUMN CONSISTENCY

In [ ]:
print(sales2020.columns.tolist())
print(sales2021.columns.tolist())
print(sales2022.columns.tolist())## TO LIST COVERTS CERTAIN DATASTRUCTURES INTO NORMAL PYTHON

['OrderDate', 'StockDate', 'OrderNumber', 'ProductKey', 'CustomerKey', 'TerritoryKey', 'OrderLineItem', 'OrderQuantity']
['OrderDate', 'StockDate', 'OrderNumber', 'ProductKey', 'CustomerKey', 'TerritoryKey', 'OrderLineItem', 'OrderQuantity']
['OrderDate', 'StockDate', 'OrderNumber', 'ProductKey', 'CustomerKey', 'TerritoryKey', 'OrderLineItem', 'OrderQuantity']

## MERGING SALES DATA

In [13]:
sales_all = pd.concat(
    [sales2020, sales2021, sales2022],
    ignore_index=True
)

In [14]:
print("Combined Dataset Shape:", sales_all.shape)
sales_all.head()

Combined Dataset Shape: (56046, 8)

,OrderDate,StockDate,OrderNumber,ProductKey,CustomerKey,TerritoryKey,OrderLineItem,OrderQuantity
0,2020-01-01,2019-09-21,SO45080,332,14657,1,1,1
1,2020-01-01,2019-12-05,SO45079,312,29255,4,1,1
2,2020-01-01,2019-10-29,SO45082,350,11455,9,1,1
3,2020-01-01,2019-11-16,SO45081,338,26782,6,1,1
4,2020-01-02,2019-12-15,SO45083,312,14947,10,1,1

## DATASET INFORMATION

In [15]:
sales_all.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56046 entries, 0 to 56045
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   OrderDate      56046 non-null  object
 1   StockDate      56046 non-null  object
 2   OrderNumber    56046 non-null  object
 3   ProductKey     56046 non-null  int64
 4   CustomerKey    56046 non-null  int64
 5   TerritoryKey   56046 non-null  int64
 6   OrderLineItem  56046 non-null  int64
 7   OrderQuantity  56046 non-null  int64
dtypes: int64(5), object(3)
memory usage: 3.4+ MB

## MISSING VALUES

In [ ]:
missing_values = sales_all.isnull().sum()

missing_df = pd.DataFrame({
    'Column': missing_values.index,
    'Missing Values': missing_values.values
})

missing_df[missing_df['Missing Values'] > 0]

Empty DataFrame
Columns: [Column, Missing Values]
Index: []

In [17]:
missing_percentage = (
    sales_all.isnull().sum()
    / len(sales_all)
) * 100

missing_percentage.sort_values(
    ascending=False
)

OrderDate        0.0
StockDate        0.0
OrderNumber      0.0
ProductKey       0.0
CustomerKey      0.0
TerritoryKey     0.0
OrderLineItem    0.0
OrderQuantity    0.0
dtype: float64

## DUPLICATED RECORDS

In [18]:
duplicates = sales_all.duplicated().sum()

print(
    f"Duplicate Rows: {duplicates}"
)

Duplicate Rows: 0

In [19]:
sales_all.drop_duplicates(
    inplace=True
)

In [20]:
sales_all.duplicated().sum()

np.int64(0)

## DATA TYPE CONVERSION

In [21]:
sales_all.columns

Index(['OrderDate', 'StockDate', 'OrderNumber', 'ProductKey', 'CustomerKey',
       'TerritoryKey', 'OrderLineItem', 'OrderQuantity'],
      dtype='object')

In [22]:
sales_all['OrderDate'] = pd.to_datetime(
    sales_all['OrderDate']
)

In [23]:
sales_all.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56046 entries, 0 to 56045
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   OrderDate      56046 non-null  datetime64[ns]
 1   StockDate      56046 non-null  object
 2   OrderNumber    56046 non-null  object
 3   ProductKey     56046 non-null  int64
 4   CustomerKey    56046 non-null  int64
 5   TerritoryKey   56046 non-null  int64
 6   OrderLineItem  56046 non-null  int64
 7   OrderQuantity  56046 non-null  int64
dtypes: datetime64[ns](1), int64(5), object(2)
memory usage: 3.4+ MB

## BASIC DATA QUALITY CHECKS

In [24]:
numeric_columns = sales_all.select_dtypes(
    include=np.number
).columns

sales_all[numeric_columns].describe()

         ProductKey   CustomerKey  TerritoryKey  OrderLineItem  OrderQuantity
count  56046.000000  56046.000000  56046.000000   56046.000000   56046.000000
mean     438.962103  18843.645559      6.254666       1.903151       1.501873
std      118.612352   5412.449843      2.958005       1.021006       0.612379
min      214.000000  11000.000000      1.000000       1.000000       1.000000
25%      360.000000  14016.000000      4.000000       1.000000       1.000000
50%      479.000000  18157.000000      7.000000       2.000000       1.000000
75%      529.000000  23425.750000      9.000000       2.000000       2.000000
max      606.000000  29483.000000     10.000000       8.000000       3.000000

In [25]:
sales_all[
    sales_all['OrderQuantity'] < 0
]

Empty DataFrame
Columns: [OrderDate, StockDate, OrderNumber, ProductKey, CustomerKey, TerritoryKey, OrderLineItem, OrderQuantity]
Index: []

## SUMMARY STATISTICS

In [26]:
sales_all.describe()

,OrderDate,ProductKey,CustomerKey,TerritoryKey,OrderLineItem,OrderQuantity
count,56046,56046.000000,56046.000000,56046.000000,56046.000000,56046.000000
mean,2021-12-16 19:51:03.526388992,438.962103,18843.645559,6.254666,1.903151,1.501873
min,2020-01-01 00:00:00,214.000000,11000.000000,1.000000,1.000000,1.000000
25%,2021-10-06 00:00:00,360.000000,14016.000000,4.000000,1.000000,1.000000
50%,2022-01-11 00:00:00,479.000000,18157.000000,7.000000,2.000000,1.000000
75%,2022-04-12 00:00:00,529.000000,23425.750000,9.000000,2.000000,2.000000
max,2022-06-30 00:00:00,606.000000,29483.000000,10.000000,8.000000,3.000000
std,NaN,118.612352,5412.449843,2.958005,1.021006,0.612379

In [30]:

import os
print(os.getcwd())

c:\Users\DELL\OneDrive\Desktop\apexplanet2\notebooks

In [39]:
import os

print("Current Folder:", os.getcwd())
print("Processed Exists:", os.path.exists("../data/processed"))
print("Data Exists:", os.path.exists("../data"))

try:
    print(os.listdir("../data"))
except Exception as e:
    print(e)

Current Folder: c:\Users\DELL\OneDrive\Desktop\apexplanet2\notebooks
Processed Exists: True
Data Exists: True
['processed', 'raw']

In [41]:
sales_all.to_csv(
    "../data/processed/Sales_All.csv",
    index=False
)

print("Sales_All.csv saved successfully")

Sales_All.csv saved successfully